services:
  postgres-primary:
    image: postgres:13
    container_name: postgres-primary
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: task_app_development # Specify the database to be created
    ports:
      - "15432:5432"
    volumes:
      - pgdata_primary:/var/lib/postgresql/data

  postgres-replica:
    image: postgres:13
    container_name: postgres-replica
    environment:
      POSTGRES_USER: postgres
    ports:
      - "15433:5432"
    volumes:
      - pgdata_replica:/var/lib/postgresql/data
    depends_on:
      - postgres-primary

  web:
    build: .
    container_name: rails-app
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0"
    volumes:
      - .:/myapp # Mount current directory to /myapp in the container
    ports:
      - "3000:3000" # Expose port 3000 for the Rails app
    depends_on:
      - postgres-primary # Ensure PostgreSQL is started before Rails app
    # environment:
    #   SECRET_KEY_BASE: ${SECRET_KEY_BASE}
    env_file:
      - .env

volumes:
  pgdata_primary:
  pgdata_replica:
