FROM ruby:3.3.6-slim

# Set working directory
WORKDIR /app

# Install dependencies
RUN apt-get update -qq && \
  apt-get install --no-install-recommends -y nodejs postgresql-client && \
  rm -rf /var/lib/apt/lists/*

# Install gems
COPY Gemfile Gemfile.lock ./
RUN bundle install

# Copy application code
COPY . .

# Expose port for Rails server
EXPOSE 3000

# Start the Rails server
CMD ["rails", "server", "-b", "0.0.0.0"]
